services:
  - type: web
    name: bls-selfie-server
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
    domains:
      - bisselfie.uk
      - www.bisselfie.uk